INSERT INTO
  ZONA
VALUES
  ('Unicamp'),
  ('Barão Geraldo'),
  ('Cambuí'),
  ('Taquaral'),
  ('Term. Ramos De Azevedo'),
  ('Catedral'),
  ('Rosario'),
  ('Praça Bento Quirino'),
  ('Praça Matriz Do Carmo'),
  ('Viaduto Miguel V. Cury'),
  ('Carrefour Eldorado'),
  ('Mercado, C. C. C. Carlos Gomes'),
  ('Casa De Saude'),
  ('Jardim Carlos Gomes'),
  ('Largo Do Para'),
  ('Maternidade'),
  ('Praça Luiz De Camoes'),
  ('Largo Santa Cruz'),
  ('Avenida Joao Jorge'),
  ('Bierrembach De Castro'),
  ('Praça Joao Milani (Rex)'),
  ('Castelo'),
  ('Praça Maua'),
  ('Dom Barreto'),
  ('Bonfim'),
  ('Sao Bernardo'),
  ('Shopping Iguatemi'),
  ('Nova Campinas'),
  ('Vila Teixeira'),
  ('Extra / Amoreiras'),
  ('Aeroporto De Viracopos'),
  ('Swift / Extra Aboliçao'),
  ('Sousas'),
  ('Guarani'),
  ('Jardim Bela Vista'),
  ('Jardim Leonor'),
  ('Novo Cambui'),
  ('Jd. Itatinga'),
  ('Jardim Santana'),
  ('Cidade Judiciaria'),
  ('Vila Boa Vista'),
  ('Jardim Dos Oliveiras'),
  ('Jardim Proença'),
  ('Vila Nova'),
  ('Jardim Aurelia'),
  ('Circulo Militar'),
  ('Parque Industrial'),
  ('Jardim Garcia'),
  ('Jardim Flamboyant'),
  ('Jardim Iv Centenario'),
  ('Jardim Nova Europa'),
  ('Lagoa Do Taquaral'),
  ('Vila Costa E Silva'),
  ('Condominio Alphaville I'),
  ('Galleria Shopping'),
  ('Sleep Inn Galleria Hotel'),
  ('Shopping Pq. D. Pedro'),
  ('Julio De Mesquita'),
  ('Andrade Neves'),
  ('Hospital Ouro Verde'),
  ('Viaduto Sao Paulo (Laurao)'),
  ('Barreto Leme - Centro'),
  ('Vila Padre Anchieta'),
  ('Carrefour Valinhos'),
  ('Hotel Sol Inn (Barao Geraldo)'),
  ('Praça Salim Jorge'),
  ('Shopping Pq. Das Bandeiras'),
  ('Praça Capital'),
  ('Swiss Park'),
  ('Mansoes Sto. Antonio');